-- CreateTable
CREATE TABLE "characters" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "age" INTEGER NOT NULL,
    "birth_place" TEXT NOT NULL,
    "childhood_story" TEXT NOT NULL,
    "feelings_about_parents" TEXT NOT NULL,
    "parents_alive" BOOLEAN NOT NULL,
    "details_about_parents" TEXT,
    "siblings" TEXT,
    "youth_friends" TEXT,
    "marital_status" TEXT NOT NULL,
    "conjugal_history" TEXT,
    "children" TEXT,
    "education" TEXT NOT NULL,
    "profession" TEXT NOT NULL,
    "reason_for_profession" TEXT NOT NULL,
    "physical_description" TEXT NOT NULL,
    "distinctive_trait" TEXT NOT NULL,
    "goal" TEXT,
    "reason_for_goal" TEXT,
    "plan_if_successful" TEXT,
    "plan_if_failed" TEXT,
    "biggest_obstacle" TEXT,
    "overcoming_obstacle" TEXT,
    "change_in_world" TEXT,
    "change_in_self" TEXT,
    "fears" TEXT,
    "self_description" TEXT,
    "attitude_towards_world" TEXT NOT NULL,
    "attitude_towards_people" TEXT NOT NULL,
    "attitude_towards_groups" TEXT,
    "leisure_activities" TEXT,
    "clothing_preferences" TEXT,
    "work_preferences" TEXT,
    "favorite_food" TEXT,
    "hobbies" TEXT,
    "pet" TEXT,
    "ideal_company" TEXT,
    "type_of_lover" TEXT,
    "residence_location" TEXT NOT NULL,
    "climate" TEXT,
    "reason_for_residence" TEXT,
    "common_problems" TEXT,
    "daily_routine" TEXT,
    "image" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3),

    CONSTRAINT "characters_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "characters_name_key" ON "characters"("name");
